---
# Ansible Linter rules
mock_modules:
  - community.vmware.vmware_guest_snapshot

# Exclude paths from linter
exclude_paths:
  - '${PWD}/.github/'
  - '${PWD}/changelogs/'
  - '${PWD}/docs/'
  - '.github/'
  - 'changelogs/'
  - 'docs/'
  - 'collections/'

# Ansible Linter rules
skip_list:
  - yaml[colons] # Violations reported by yamllint.
  - yaml[line-length]  # Violations reported by yamllint.

warn_list:  # or 'skip_list' to silence them completely
  - git-latest # Allow for newest git version
  - package-latest # Allow newest package version
  - risky-file-permissions  # File permissions unset or incorrect.
  - risky-shell-pipe  # Shells that use pipes should set the pipefail option.
  - template-instead-of-copy  # Templated files should use template instead of copy
  - command-instead-of-shell  # Use shell only when shell functionality is required.
  - no-changed-when # temp until updated all tasks
  - sanity[cannot-ignore] # cope with shebang test bug

...
