---
# tasks file for snapshot
- name: Import aws tasks
  ansible.builtin.import_tasks: aws.yml
  when: snapshot is match('aws')

- name: Import azure tasks
  ansible.builtin.import_tasks: azure.yml
  when: snapshot is match('azure')

- name: Import gcp tasks
  ansible.builtin.import_tasks: gcp.yml
  when: snapshot is match('gcp')

- name: Import lvm tasks
  ansible.builtin.import_tasks: lvm.yml
  when: snapshot is match('lvm')

- name: Import nutanix tasks
  ansible.builtin.import_tasks: nutanix.yml
  when: snapshot is match('nutanix')

- name: Import vcenter tasks
  ansible.builtin.import_tasks: vcenter.yml
  when: snapshot is match('vcenter')

...
