---
# defaults file for upgrade
log_directory: /var/log/ripu
log_file: "{{ log_directory }}/ripu.log"

# leapp_upgrade_type: connected
leapp_upgrade_type: disconnected

leapp_upgrade_opts: "{{ '--no-rhsm' if leapp_upgrade_type == 'connected' else '' }}"

result_filename: '/var/log/leapp/leapp-report.txt'

rhel_7_upgrade_dest_version: '8.6'
rhel_8_upgrade_dest_version: '9.0'

# leapp_repos_enabled: []
leapp_repos_enabled:
  - codeready-builder-for-rhel-{{ ansible_distribution_major_version | int + 1 }}-x86_64-rpms
  - satellite-client-6-for-rhel-{{ ansible_distribution_major_version | int + 1 }}-x86_64-rpms

# Desired selinux mode post Leapp upgrade.
selinux_mode: enforcing
# selinux_mode: permissive
# selinux_mode: disabled
...
