---
# defaults file for upgrade
# leapp_upgrade_type: connected
leapp_upgrade_type: disconnected

leapp_upgrade_opts: "{{ '--no-rhsm' if leapp_upgrade_type == 'connected' else '' }}"

result_filename: '/var/log/leapp/leapp-report.txt'

rhel_7_upgrade_dest_version: '8.6'
rhel_8_upgrade_dest_version: '9.0'

leapp_repos_enabled: []
# leapp_repos_enabled:
#   - satellite-client-6-for-rhel-{{ ansible_distribution_major_version | int + 1 }}-x86_64-rpms

satellite_organization: Example
satellite_activation_key_post_leapp: rhel{{ ansible_distribution_major_version }}_prod

# Desired selinux mode post Leapp upgrade.
# selinux_mode: enforcing
# selinux_mode: permissive
# selinux_mode: disabled
# Default selinux_mode to what was found during the pre-upgrade analysis automation.
selinux_mode: "{{ ansible_facts.ansible_local.pre_ripu.selinux.config_mode }}"

# System-wide cryptographic policies
# set_crypto_policies: false
set_crypto_policies: true
# crypto_policy: DEFAULT
crypto_policy: FUTURE
# crypto_policy: DEFAULT:SHA1
...
