---
- name: Default upgrade_inhibited to false
  ansible.builtin.set_fact:
    upgrade_inhibited: false

- name: Collect human readable report results
  ansible.builtin.slurp:
    src: "{{ result_filename }}"
  register: results

- name: Collect JSON report results
  ansible.builtin.slurp:
    src: "{{ result_filename_json }}"
  register: results

- name: Parse report results
  ansible.builtin.set_fact:
    leapp_report_txt: "{{ results.content | b64decode | split('\n') }}"
    leapp_report_json: "{{ results.content | b64decode | from_json }}"

- name: Check for inhibitors
  ansible.builtin.set_fact:
    upgrade_inhibited: true
  when: "'inhibitor' in item.flags"
  loop: "{{ leapp_report_json.entries }}"
...
