---
# tasks file for upgrade
# TODO: Include tasks for RHEL 6 to 7 non-leapp upgrade
# - name: Include tasks for upgrade using redhat-upgrade-tool
#   ansible.builtin.include_tasks: upgrade-redhat-upgrade-tool.yml
#   when: ansible_distribution_major_version|int < 7

- name: Include tasks for leapp upgrade
  ansible.builtin.include_tasks: leapp-upgrade.yml
  when: ansible_distribution_major_version|int >= 7

- name: Include post upgrade validation
  ansible.builtin.include_tasks: upgrade-validation.yml

- name: Include tasks for leapp post upgrade
  ansible.builtin.include_tasks: leapp-post-upgrade.yml
  when: ansible_facts.ansible_local.pre_ripu.distribution_major_version|int >= 7

- name: RIPU in-place OS upgrade is done
  ansible.builtin.debug:
    msg: 'The in-place OS upgrade is now complete. Engage your partner teams to begin application validation.'
...
