---
# TODO: Having issues with community.general.redhat_subscription and subscription-manager on RHEL 6.
- name: "Register to post upgrade activation key"
  ansible.builtin.shell: >
    subscription-manager register
    --org="{{ satellite_organization }}"
    --activationkey="{{ satellite_activation_key_post_leapp }}"
    --force
  register: sub_man_reg
  when: leapp_upgrade_type == 'disconnected'
  failed_when: false

- name: Include check-for-old-packages.yml
  ansible.builtin.include_tasks: check-for-old-packages.yml

# TODO: Remove enough old el6 packages that yum update can complete successfully.

# TODO: Remove el6 kernels?

# TODO: Update GRUB Legacy to GRUB 2.

- name: Include update-and-reboot.yml
  ansible.builtin.include_tasks: update-and-reboot.yml

# TODO: If Samba is installed run testparm on /etc/samba/smb.conf?

...
