---
# tasks file for analysis
- name: Initialize lock and logging
  ansible.builtin.import_role:
    name: infra.leapp.logging
  vars:
    job_name: 'RIPU preupgrade analysis'

- name: /etc/ansible/facts.d directory exists
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Capture current ansible_facts for validation after upgrade
  ansible.builtin.copy:
    content: "{{ ansible_facts | ansible.builtin.combine({'ansible_local': {}}) }}"
    dest: /etc/ansible/facts.d/pre_ripu.fact

# TODO: Include tasks for RHEL 6 to 7 non-leapp upgrade
# - name: Include tasks for preupg assistant analysis
#   ansible.builtin.include_tasks: analysis-preupg.yml
#   when: ansible_distribution_major_version|int < 7

- name: Include tasks for leapp preupgrade analysis
  ansible.builtin.include_tasks: analysis-leapp.yml
  when: ansible_distribution_major_version|int >= 7
...
