---
- name: Roleback
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  tasks:
    - name: Initialize lock and logging
      ansible.builtin.import_role:
        name: infra.leapp.logging
      vars:
        job_name: 'RIPU snapshot rollback'

    - name: Perform snapshot rollback
      ansible.builtin.import_role:
        name: infra.leapp.rollback
...
