---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Release

on:
  release:
    types:
      - published

jobs:
  pre-commit:
    uses: oamg/ansible-leapp/.github/workflows/pre-commit.yml@main
    with:
      collection_namespace: infra
      collection_name: leapp
      collection_version: ${{ vars.GITHUB_REF }}
  sanity:
    uses: oamg/ansible-leapp/.github/workflows/ansible-test.yml@main
    with:
      collection_namespace: infra
      collection_name: leapp
      collection_version: ${{ vars.GITHUB_REF }}
  prechecks:
    needs:
      - pre-commit
      - sanity
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.pre-commit.result }}',
          '${{ needs.sanity.result }}',
          ]) == {'success'}"
  infra_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install --upgrade ansible-core

      - name: Build collection
        run: ansible-galaxy collection build -vvv
        shell: bash
        working-directory: ${{ vars.GITHUB_PATH }}

      - name: Install collection
        run: ansible-galaxy collection install ./infra-leapp-${{ vars.GITHUB_REF }}.tar.gz -p /home/runner/collections
        shell: bash
        working-directory: ${{ vars.GITHUB_PATH }}

      - name: Publish to galaxy
        run: ansible-galaxy collection publish --api-key=${{ secrets.galaxy_api_key }} ${{ steps.build.outputs.tar_file }}

      - name: Upload files to tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.token }}
          file: ${{ steps.build.outputs.tar_file }}
          tag: ${{ github.ref }}
          overwrite: true
  changelog:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install --upgrade ansible-core antsibull-changelog

      - name: Run changelog
        run: antsibull-changelog release --verbose --version ${{ vars.GITHUB_REF }}

      - name: Create Pull Request
        id: prcreate
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.token }}
          commit-message: Update changelog ${{ github.ref }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: devel
          branch: changelog-patches
          delete-branch: true
          title: '[RELEASE] Update changelog ${{ github.ref }}'
          body: |
            Update changelog
            - Updated with changelog for release ${{ github.ref }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            changelog
            automated pr
          draft: false
...
